### ISSUE TITLE
When copying multiple files, provide a directory as destination

### ISSUE THREAD

**Issue by Ryuno-Ki** [sebs/generator-hexo-plugin#1]
Hey,

just tried out to write a plugin, but there is so few documentation about how to accomplish that.
However, looks like your yeoman generator is broken:

```
Sun, 23 Sep 2018 12:27:51 GMT yeoman:generator Queueing prompting in prompting
Sun, 23 Sep 2018 12:27:51 GMT yeoman:generator Queueing writing in writing
Sun, 23 Sep 2018 12:27:51 GMT yeoman:generator Queueing install in install
Sun, 23 Sep 2018 12:27:51 GMT yeoman:generator Running prompting
Sun, 23 Sep 2018 12:27:55 GMT yeoman:generator Running writing
Sun, 23 Sep 2018 12:27:55 GMT yeoman:generator An error occured while running writing { AssertionError [ERR_ASSERTION]: When copying multiple files, provide a directory as destination
    at EditionInterface.exports.copy ($HOME/src/hexo-plugin-social/node_modules/mem-fs-editor/lib/actions/copy.js:34:5)
    at EditionInterface.module.exports [as copyTpl] ($HOME/src/hexo-plugin-social/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.writing ($HOME/src/hexo-plugin-social/node_modules/generator-hexo-plugin/generators/app/index.js:84:13)
    at Object.<anonymous> ($HOME/src/hexo-plugin-social/node_modules/yeoman-generator/lib/index.js:417:23)
    at $HOME/src/hexo-plugin-social/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at $HOME/src/hexo-plugin-social/node_modules/run-async/index.js:24:19
    at $HOME/src/hexo-plugin-social/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: When copying multiple files, provide a directory as destination
    at EditionInterface.exports.copy ($HOME/src/hexo-plugin-social/node_modules/mem-fs-editor/lib/actions/copy.js:34:5)
    at EditionInterface.module.exports [as copyTpl] ($HOME/src/hexo-plugin-social/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.writing ($HOME/src/hexo-plugin-social/node_modules/generator-hexo-plugin/generators/app/index.js:84:13)
    at Object.<anonymous> ($HOME/src/hexo-plugin-social/node_modules/yeoman-generator/lib/index.js:417:23)
    at $HOME/src/hexo-plugin-social/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at $HOME/src/hexo-plugin-social/node_modules/run-async/index.js:24:19
    at $HOME/src/hexo-plugin-social/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
```

That's the output with `DEBUG=yeoman:generator`. I was using v0.0.12.

**Comment by sebs** [comment]
Thanks, i will check it out. Its anyway on my "todolist". Thank you for reporting.
